version: "3.8"
services:
  db:
    container_name: postgres_container
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bitrush
    ports:
      - "5432:5432"
      
  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=gcgranja@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=gabrielg28
      - PGADMIN_LISTEN_PORT=5050

    ports:
      - "5050:5050"

volumes:
  data:
